### ISSUE TITLE
StellarGraph does not have usecase/genes Branch

### ISSUE THREAD

**Issue by tedzhouhk** [esugis/hena#1]
Thanks for providing the awesome open sourced code!
When I try the case study, in step 5 in running the experiment

`Clone the stellargraph repository git clone https://github.com/stellargraph/stellargraph.git -b usecase/genes`

However, it seems that the current version of stellargraph does not have this branch. Is there any workaround? Thanks in advance!

**Comment by esugis** [comment]
Hi,
HENA case study (gene classification task) was developed quite some time ago together with other first use cases for stellargraph. Stellargraph has evolved since then. Please contact stellargraph developers directly (https://www.stellargraph.io/about-us) about this issue.
